```
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { RankedCandidate } from "@/types";

declare module "jspdf" {
    interface jsPDF {
        autoTable: (options: Record<string, unknown>) => jsPDF;
    }
}

export const exportToPDF = (jobTitle: string, candidates: RankedCandidate[]) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // slate-800
    doc.text("HireScreen: Candidate Rank Report", 14, 22);

    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Job Title: ${ jobTitle } `, 14, 32);
    doc.text(`Date Generated: ${ date } `, 14, 38);
    doc.text(`Top ${ candidates.length } Candidates`, 14, 44);

    // Table
    const tableData = candidates.map((c) => [
        c.rank,
        c.name,
        `${ c.score }% `,
        c.matchReasons.map((r) => `• ${ r.reason } `).join("\n"),
        c.filename,
    ]);

    doc.autoTable({
        startY: 52,
        head: [["Rank", "Name", "Match Score", "Match Reasons / Citations", "Source File"]],
        body: tableData,
        headStyles: {
            fillColor: [79, 70, 229], // indigo-600
            fontSize: 10,
            halign: "center",
        },
        columnStyles: {
            0: { cellWidth: 15, halign: "center" },
            1: { cellWidth: 35, fontStyle: "bold" },
            2: { cellWidth: 25, halign: "center" },
            3: { cellWidth: "auto" },
            4: { cellWidth: 30, fontSize: 8 },
        },
        styles: {
            fontSize: 9,
            cellPadding: 4,
            valign: "middle",
        },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(
            `Generated by HireScreen AI • Page ${ i } of ${ pageCount } `,
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: "center" }
        );
    }

    doc.save(`HireScreen_Candidates_${ jobTitle.replace(/\s+/g, "_") }.pdf`);
};
